#!/bin/sh

IPs="5.9.105.86 fddf:ebfd:a801:4859::c03 fda0:747e:ab29:4859::c03 62.141.34.126 5.135.22.78"

for ip in $IPs ; do 
  curl -s --keepalive-time 300 --ssl-reqd --tlsv1.2 --tcp-nodelay --cacert /etc/ff-cacert.pem --resolve center.ffnrw:10643:"$ip" https://center.ffnrw:10643/"$@" && exit 0
done
exit 1
