#!/bin/sh

IPs="89.163.132.19 2001:4ba0:babe:0778::1 fddf:ebfd:a801:4859::c03 62.141.34.126 5.135.22.78"

for ip in $IPs ; do 
  curl -s --keepalive-time 300 --tcp-nodelay --resolve center.ffnrw:10680:"$ip" http://center.ffnrw:10680/"$@" && exit 0
done
exit 1
