#!/bin/sh /etc/rc.common

START=96

start () {
	DONE=0
	sleep 10
    echo 0 > /tmp/randomdelay
	for i in 1 2 3 4 5 6 7 8 9 10
	do
		ping -q -I br-wan 8.8.8.8 -c 4 -W 5 >/dev/null 2>&1
		if test $? -eq 0; then
			iw dev client0 scan passive 2>&1 > /dev/null || true
			iw dev client1 scan passive 2>&1 > /dev/null || true
			sh /usr/sbin/ff-stats-wlanscan > /tmp/wlanscan || true
	  		sh /usr/sbin/ff-stats
	  		DONE=1
	  		break
	  	else
			ipv6_subnet="$(lua -e 'print(require("gluon.site_config").prefix6)' | sed -e 's/\/64//')"
			if [ ! -z "$ipv6_subnet" ]; then
	  			ipv6_anycast="${ipv6_subnet}ac1"
	  			ping6 "$ipv6_anycast" -c 10 >/dev/null 2>&1
	  			returnval="$?"
			fi
			if [ "$returnval" -eq 0 ] && [ ! -z "$ipv6_subnet" ]; then
	  			iw dev client0 scan passive 2>&1 > /dev/null || true
				iw dev client1 scan passive 2>&1 > /dev/null || true
				sh /usr/sbin/ff-stats-wlanscan > /tmp/wlanscan || true
	  			sh /usr/sbin/ff-stats
	  			DONE=1
	  			break
			fi
		fi
		sleep 10
	done
	if [ "$DONE" -eq "0" ]; then
		iw dev client0 scan passive 2>&1 > /dev/null || true
		iw dev client1 scan passive 2>&1 > /dev/null || true
		sh /usr/sbin/ff-stats-wlanscan > /tmp/wlanscan || true
		( sh /usr/sbin/ff-offline-ssid 60 )& || true
		sh sh /usr/sbin/ff-stats || true
	fi
    awk "BEGIN{srand(); print(int(rand()*299));}" > /tmp/randomdelay
}
